const UPLOAD_POSTS = 'UPLOAD_POSTS';
const TOGGLE_BOOKED = 'TOGGLE_BOOKED';
const DELETE_POST = 'DELETE_POST';
const ADD_POST = 'ADD_POST';
export { UPLOAD_POSTS, TOGGLE_BOOKED, DELETE_POST, ADD_POST };
